name: CI Workflow - Back

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and run tests with Maven
        run: mvn clean test
        working-directory: ./back

      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report
        working-directory: ./back

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/target/site/jacoco

  sonarQube:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11 (pour le backend Spring Boot)
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install dependencies and run tests (backend)
        run: |
          cd backend
          ./mvnw clean verify

      - name: Run SonarCloud analysis (backend)
        run: |
          cd backend
          ./mvnw sonar:sonar \
            -Dsonar.projectKey=your_project_key_backend \
            -Dsonar.organization=your_organization_key \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}        
