name: CI Workflow - Back

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build back-end
        run: mvn clean compile
        working-directory: ./back

      - name: Build and run tests with Maven
        run: mvn clean test
        working-directory: ./back

      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report
        working-directory: ./back

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/target/site/jacoco

  sonarQube:
    name: SonarQube Back
    needs: backend-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pour un meilleur contexte d'analyse
          ref: main            # Spécifie la branche 'main'
          fetch-tags: true     # (Optionnel) Récupère également les tags

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17  # Adaptez selon votre configuration
          distribution: 'zulu'


      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        working-directory: back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -X verify org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
            -Dsonar.projectKey=Honayme_OC-CI-CD-back \
            -Dsonar.organization=bobappteam2024-back \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.branch.name=${GITHUB_REF_NAME} \
            -Dsonar.java.binaries=target/classes
            -Dsonar.mainBranch=main

  build-and-push:
    name: Build and Push Back-End Docker Image
    needs: sonarQube
    runs-on: ubuntu-latest
    if: ${{github.event.review.state == 'approved' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build the application
        run: mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: back
          file: back/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
