name: CI Workflow - Front

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./front

      - name: Run tests and generate coverage report
        run: npm test
        working-directory: ./front

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage  # Nom mis à jour pour correspondre
          path: front/coverage

  sonarQube:
    name: SonarQube Front
    needs: frontend-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1  # Utilisation de la version stable v1
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=Honayme_OC-CI-CD-Front
            -Dsonar.organization=bobappteam2024
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov-report/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


