name: CI Workflow - Front

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./front

      - name: Run tests and generate coverage report
        run: npm test
        working-directory: ./front

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage

  sonarQube:
    name: SonarQube Front
    needs: frontend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          set-java-home: true  # Assure que JAVA_HOME est défini

      - name: Verify Java Version
        run: java -version

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Honayme_OC-CI-CD
            -Dsonar.organization=bobappteam2024
            -Dsonar.sources=./front/src
            -Dsonar.tests=./front/src
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov-report/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
